### ISSUE TITLE
Create tooltip for REPORT BUG link

### ISSUE THREAD

**Issue by lboka** [opentelekomcloud/otcdocstheme#183]
Hi,
It would be helpful to have "tooltip" , when user hover mouse over the icon or link for REPORT BUG.  There could be mentioned, that this should be used just for DOCUMENTATION RELATED issue, not for general platform or service issue.  It already happed that users try to report their issues related to their resources  via this link.

![image](https://github.com/opentelekomcloud/otcdocstheme/assets/96316177/e19cc05a-1b2b-42c7-9a9f-e55ae34ad2b3)

**Comment by tischrei** [comment]
Good hint, we will try to improve the button.

**Comment by tischrei** [comment]
Hi @lboka ,
I tried tooltips, but looks ugly. We will rename it to "Report Documentation Bug". This should be clear enough for everyone.

Are you with the solution?
