### ISSUE TITLE
search bar

### ISSUE THREAD

**Issue by Nils-Magnus** [opentelekomcloud/otcdocstheme#194]
1. once magnifier lens icon is clicked, replace "Search" in the grey search bar with "type to search ..."
2. once magnifier lens icon is clicked, move focus to search bar  immediately
3. keep search bar bg dark grey ("active", focussed), even, if mouse is not longer hovering the search bar

**Comment by tischrei** [comment]
First 2 topics can be improved and will be improved. Last topic is not possible with the Scale compliant element.
