### ISSUE TITLE
pdf creation failed with pdflatex

### ISSUE THREAD

**Issue by eumel8** [opentelekomcloud/otcdocstheme#2]
tried to include otcdocstheme in sphinx project, but pdf creation on readthedocs failed with that theme:

``
! Text line contains an invalid character.
l.10 \catcode`^^^
                 ^00a0\active\protected\def^^^^00a0{\leavevmode\nobreak\ }
``
see https://readthedocs.org/projects/ansible-otc/builds/7713603/

**Comment by gtema** [comment]
@eumel8, can you please try to update the theme with the latest changes from upstream? Perhaps it will even fix this issue

**Comment by eumel8** [comment]
It's build, but without DT logo on the front page:
https://readthedocs.org/projects/ansible-otc/downloads/pdf/dev/
https://readthedocs.org/projects/ansible-otc/builds/9748183/

Just curious the logo is on some pages and already on a local build.

**Comment by tischrei** [comment]
we are reworking the whole theme.
