### ISSUE TITLE
Top bar is hiding the headings in CHROME.

### ISSUE THREAD

**Issue by lboka** [opentelekomcloud/otcdocstheme#201]
I can see that top bar on the page is covering the headings after click on the PAGE CONTENTS menu on the right.: 

Example: RDS -> UMN -> Introduction -> Basic Concepts
https://docs-int.otc-service.com/relational-database-service/umn/introduction/basic_concepts.html#rds-01-0015

The main title is displayed correctly after click on the LEFT MENU.
<img width="943" alt="image" src="https://github.com/opentelekomcloud/otcdocstheme/assets/96316177/b7b4d884-70f3-48b9-8958-befb0358c155">

Heading of the section that was picked on the PAGE CONTENTS menu on the right is hidden.
<img width="946" alt="image" src="https://github.com/opentelekomcloud/otcdocstheme/assets/96316177/d86fe246-ac0b-42f5-914f-de7d6b22b520">

**Comment by tischrei** [comment]
Thanks for the issue. We are trying to fix that.
