### ISSUE TITLE
Make header font color lighter

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud/otcdocstheme#49]
On pages with lot of content visual separation of subchapters is not optimal. It can be improved by making color of the header few shades lighter (like on OpenStack): https://docs-beta.otc.t-systems.com/python-otcextensions/sdk/proxies/dcs.html vs https://docs.openstack.org/openstacksdk/latest/user/proxies/block_storage_v3.html

**Comment by tischrei** [comment]
I generally disagree, because I like that h1 is bolder in comparison to the other headlines and also aligns with the sidebar header. Please compare it again after looking into the attached PR.

**Comment by gtema** [comment]
it's not about lighter, but using a lighter "color"

**Comment by tischrei** [comment]
> it's not about lighter, but using a lighter "color"

done
