### ISSUE TITLE
Analyze visualization

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud/otcdocstheme#50]
Analysis of https://docs-beta.otc.t-systems.com/octavia-proxy/configuration/configref.html need to be done. It doesn't look optimal.
https://docs-beta.otc.t-systems.com/octavia-proxy/user/feature-classification/index.html

**Comment by tischrei** [comment]
close?

**Comment by gtema** [comment]
neah, it still look messy (first link). Few ideas:
- increase margin between `dl` elements (`dl: margin-bottom` increase to 2 rem)
- make `dl.option dt` (or alternatively `dt.sig-object`since we have it already) visually different (bigger, or different font, different color, etc) (example: font-size: 1.5rem, drop bold)
<img width="960" alt="Screenshot 2022-05-02 at 08 44 49" src="https://user-images.githubusercontent.com/16461884/166194850-029dd8ad-0e2c-4908-8dfb-98a250e26e13.png">


Looking at the page now I can not visually separate single options from each other

**Comment by tischrei** [comment]
Referenz for the issue: https://docs.openstack.org/octavia/latest/configuration/configref.html
